---
name: 02 – Workflow Events
on:
  #push:
  workflow_dispatch:
  #pull_request:
  #  branches:
  #    - test
  schedule:
    #- cron: "*/20 * * * *"
    - cron: "0 0 * * 3"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Zostałem uruchomiony przez zdarzenie ${{github.event_name}}"