---
name: 04 - Docker Web CI - with actions
on:
  push:
    branches: docker
  pull_request:
    branches: docker
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 04-praca-z-zewnetrzymi-akcjami/docker-app-02
    
    env:
      IMAGE_NAME: webapp
      IMAGE_TAG: ${{github.sha}}
      host_port: 8080
      container_port: 80

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.IMAGE_NAME}}
          tags: |
            type=raw, value=${{env.TAG}}

      - name: Build image (local)
        uses: docker/build-push-action@v6
        with:
          context: 04-praca-z-zewnetrzymi-akcjami/docker-app-02/Dockerfile
          push: false
          load: true
          tags: ${{env.IMAGE_NAME}}:${{env.TAG}}

      - name: Compose up
        uses: isbang/compose-action@v2
        with:
          compose-file: 04-praca-z-zewnetrzymi-akcjami/docker-app-02/docker-compose.yml
          down-flags: --volumes --remove-orphans

      - name: URL Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:${{env.host_port}}/
          max-attempts: 30
          retry-delay-seconds: 1
          follow-redirects: false

      - name: GET /
        id: page
        uses: satak/webrequest-action@v1.2.4
        with:
          url: http://localhost:${{env.host_port}}/
          method: GET

      - name: Assert page contains expected text
        uses: actions/github-script@v7
        with:
          script: |
            const body = `${{steps.page.outputs.output}}`.toLowerCase();
            if (!body.includes("cw04 github actions")) {
              core.setFailed("Strona nie zawiera oczekiwanego tekstu");
            }
      
      - name: GET /assets/wall.jpg
        id: img
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://localhost:${{env.host_port}}/assets/wall.jpg
          method: GET
          timeout: 30000

      - name: Assert image 200
        uses: actions/github-script@v7
        with:
          script: |
            const status = Number(`${{steps.img.outputs.status}}`);
            if (status !== 200) {
              core.setFailed(`Oczekiwano statusu 200, otrzymano ${status}`);
            }
            const headers = `${{ steps.img.outputs.headers }}`.toLowerCase();
            if (!headers.includes('image') && !headers.includes('jpeg') && !headers.includes('jpg')) {
              core.warning('Content-Type nie wygląda na obrazek JPEG.');
            }

      - name: Docker logs (always)
        if: always()
        uses: isbang/compose-action@v2
        with:
          compose-file: 04-praca-z-zewnetrzymi-akcjami/docker-app-02/docker-compose.yml
          commands: down --volumes --remove-orphans